backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: public/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: blog-post }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Thumbnail, name: thumbnail, widget: image, choose_url: false, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - file: src/content/pages/index.md
        label: Home
        name: index
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: index-page }
          - { label: Name, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }
          - { label: Main Heading, name: heading, widget: string }
          - { label: Introduction, name: subheading, widget: text }
          - { label: Light Hero, name: heroImageLight, widget: image, choose_url: false }
          - { label: Dark Hero, name: heroImageDark, widget: image, choose_url: false, required: false }
          - { label: Hero Alt Text, name: heroImageAlt, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: src/content/pages/bio.md
        label: Bio
        name: bio
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: bio-page }
          - { label: Date, name: date, widget: datetime, required: false }
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }
          - { label: Body, name: body, widget: markdown }

      - file: src/content/pages/work.md
        label: Work
        name: work
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: bio-page }
          - { label: Date, name: date, widget: datetime, required: false }
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }
          - { label: Body, name: body, widget: markdown }

      - file: src/content/pages/blog.md
        label: Blog Index
        name: blog
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: news-page }
          - { label: Date, name: date, widget: datetime, required: false }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Introduction, name: body, widget: markdown, required: false }
